// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: axq.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlobCompression int32

const (
	BlobCompression_BLOB_COMPRESSION_NONE BlobCompression = 0
	BlobCompression_BLOB_COMPRESSION_GZIP BlobCompression = 1
)

// Enum value maps for BlobCompression.
var (
	BlobCompression_name = map[int32]string{
		0: "BLOB_COMPRESSION_NONE",
		1: "BLOB_COMPRESSION_GZIP",
	}
	BlobCompression_value = map[string]int32{
		"BLOB_COMPRESSION_NONE": 0,
		"BLOB_COMPRESSION_GZIP": 1,
	}
)

func (x BlobCompression) Enum() *BlobCompression {
	p := new(BlobCompression)
	*p = x
	return p
}

func (x BlobCompression) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlobCompression) Descriptor() protoreflect.EnumDescriptor {
	return file_axq_proto_enumTypes[0].Descriptor()
}

func (BlobCompression) Type() protoreflect.EnumType {
	return &file_axq_proto_enumTypes[0]
}

func (x BlobCompression) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlobCompression.Descriptor instead.
func (BlobCompression) EnumDescriptor() ([]byte, []int) {
	return file_axq_proto_rawDescGZIP(), []int{0}
}

type BlobEncryption int32

const (
	BlobEncryption_BLOB_ENCRYPTION_NONE BlobEncryption = 0
	BlobEncryption_BLOB_ENCRYPTION_AES  BlobEncryption = 1
)

// Enum value maps for BlobEncryption.
var (
	BlobEncryption_name = map[int32]string{
		0: "BLOB_ENCRYPTION_NONE",
		1: "BLOB_ENCRYPTION_AES",
	}
	BlobEncryption_value = map[string]int32{
		"BLOB_ENCRYPTION_NONE": 0,
		"BLOB_ENCRYPTION_AES":  1,
	}
)

func (x BlobEncryption) Enum() *BlobEncryption {
	p := new(BlobEncryption)
	*p = x
	return p
}

func (x BlobEncryption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlobEncryption) Descriptor() protoreflect.EnumDescriptor {
	return file_axq_proto_enumTypes[1].Descriptor()
}

func (BlobEncryption) Type() protoreflect.EnumType {
	return &file_axq_proto_enumTypes[1]
}

func (x BlobEncryption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlobEncryption.Descriptor instead.
func (BlobEncryption) EnumDescriptor() ([]byte, []int) {
	return file_axq_proto_rawDescGZIP(), []int{1}
}

type Blob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fid         uint64          `protobuf:"varint,1,opt,name=fid,proto3" json:"fid,omitempty"`
	FromId      uint64          `protobuf:"varint,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId        uint64          `protobuf:"varint,3,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	Name        string          `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Count       uint64          `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	Messages    []byte          `protobuf:"bytes,6,opt,name=messages,proto3" json:"messages,omitempty"`
	DbFid       uint64          `protobuf:"varint,9,opt,name=db_fid,json=dbFid,proto3" json:"db_fid,omitempty"`
	Compression BlobCompression `protobuf:"varint,7,opt,name=compression,proto3,enum=BlobCompression" json:"compression,omitempty"`
	Encryption  BlobEncryption  `protobuf:"varint,8,opt,name=encryption,proto3,enum=BlobEncryption" json:"encryption,omitempty"`
}

func (x *Blob) Reset() {
	*x = Blob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_axq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blob) ProtoMessage() {}

func (x *Blob) ProtoReflect() protoreflect.Message {
	mi := &file_axq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blob.ProtoReflect.Descriptor instead.
func (*Blob) Descriptor() ([]byte, []int) {
	return file_axq_proto_rawDescGZIP(), []int{0}
}

func (x *Blob) GetFid() uint64 {
	if x != nil {
		return x.Fid
	}
	return 0
}

func (x *Blob) GetFromId() uint64 {
	if x != nil {
		return x.FromId
	}
	return 0
}

func (x *Blob) GetToId() uint64 {
	if x != nil {
		return x.ToId
	}
	return 0
}

func (x *Blob) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Blob) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Blob) GetMessages() []byte {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *Blob) GetDbFid() uint64 {
	if x != nil {
		return x.DbFid
	}
	return 0
}

func (x *Blob) GetCompression() BlobCompression {
	if x != nil {
		return x.Compression
	}
	return BlobCompression_BLOB_COMPRESSION_NONE
}

func (x *Blob) GetEncryption() BlobEncryption {
	if x != nil {
		return x.Encryption
	}
	return BlobEncryption_BLOB_ENCRYPTION_NONE
}

type BlobMessageList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*BlobMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Fid      uint64         `protobuf:"varint,2,opt,name=fid,proto3" json:"fid,omitempty"`
}

func (x *BlobMessageList) Reset() {
	*x = BlobMessageList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_axq_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlobMessageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobMessageList) ProtoMessage() {}

func (x *BlobMessageList) ProtoReflect() protoreflect.Message {
	mi := &file_axq_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobMessageList.ProtoReflect.Descriptor instead.
func (*BlobMessageList) Descriptor() ([]byte, []int) {
	return file_axq_proto_rawDescGZIP(), []int{1}
}

func (x *BlobMessageList) GetMessages() []*BlobMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *BlobMessageList) GetFid() uint64 {
	if x != nil {
		return x.Fid
	}
	return 0
}

type BlobMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Message []byte `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Fid     uint64 `protobuf:"varint,3,opt,name=fid,proto3" json:"fid,omitempty"`
}

func (x *BlobMessage) Reset() {
	*x = BlobMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_axq_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlobMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobMessage) ProtoMessage() {}

func (x *BlobMessage) ProtoReflect() protoreflect.Message {
	mi := &file_axq_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobMessage.ProtoReflect.Descriptor instead.
func (*BlobMessage) Descriptor() ([]byte, []int) {
	return file_axq_proto_rawDescGZIP(), []int{2}
}

func (x *BlobMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BlobMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *BlobMessage) GetFid() uint64 {
	if x != nil {
		return x.Fid
	}
	return 0
}

var File_axq_proto protoreflect.FileDescriptor

var file_axq_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x78, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x88, 0x02, 0x0a, 0x04,
	0x42, 0x6c, 0x6f, 0x62, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x03, 0x66, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x64, 0x12,
	0x13, 0x0a, 0x05, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04,
	0x74, 0x6f, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x62,
	0x5f, 0x66, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x64, 0x62, 0x46, 0x69,
	0x64, 0x12, 0x32, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x42, 0x6c, 0x6f, 0x62, 0x43, 0x6f, 0x6d,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2f, 0x0a, 0x0a, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x42, 0x6c, 0x6f, 0x62,
	0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x65, 0x6e, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4d, 0x0a, 0x0f, 0x42, 0x6c, 0x6f, 0x62, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x08, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x42, 0x6c,
	0x6f, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x03, 0x66, 0x69, 0x64, 0x22, 0x49, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x62, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x66, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x66, 0x69, 0x64,
	0x2a, 0x47, 0x0a, 0x0f, 0x42, 0x6c, 0x6f, 0x62, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x15, 0x42, 0x4c, 0x4f, 0x42, 0x5f, 0x43, 0x4f, 0x4d, 0x50,
	0x52, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x19,
	0x0a, 0x15, 0x42, 0x4c, 0x4f, 0x42, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x52, 0x45, 0x53, 0x53, 0x49,
	0x4f, 0x4e, 0x5f, 0x47, 0x5a, 0x49, 0x50, 0x10, 0x01, 0x2a, 0x43, 0x0a, 0x0e, 0x42, 0x6c, 0x6f,
	0x62, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x14, 0x42,
	0x4c, 0x4f, 0x42, 0x5f, 0x45, 0x4e, 0x43, 0x52, 0x59, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4e,
	0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x42, 0x4c, 0x4f, 0x42, 0x5f, 0x45, 0x4e,
	0x43, 0x52, 0x59, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x41, 0x45, 0x53, 0x10, 0x01, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_axq_proto_rawDescOnce sync.Once
	file_axq_proto_rawDescData = file_axq_proto_rawDesc
)

func file_axq_proto_rawDescGZIP() []byte {
	file_axq_proto_rawDescOnce.Do(func() {
		file_axq_proto_rawDescData = protoimpl.X.CompressGZIP(file_axq_proto_rawDescData)
	})
	return file_axq_proto_rawDescData
}

var file_axq_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_axq_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_axq_proto_goTypes = []interface{}{
	(BlobCompression)(0),    // 0: BlobCompression
	(BlobEncryption)(0),     // 1: BlobEncryption
	(*Blob)(nil),            // 2: Blob
	(*BlobMessageList)(nil), // 3: BlobMessageList
	(*BlobMessage)(nil),     // 4: BlobMessage
}
var file_axq_proto_depIdxs = []int32{
	0, // 0: Blob.compression:type_name -> BlobCompression
	1, // 1: Blob.encryption:type_name -> BlobEncryption
	4, // 2: BlobMessageList.messages:type_name -> BlobMessage
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_axq_proto_init() }
func file_axq_proto_init() {
	if File_axq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_axq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_axq_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlobMessageList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_axq_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlobMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_axq_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_axq_proto_goTypes,
		DependencyIndexes: file_axq_proto_depIdxs,
		EnumInfos:         file_axq_proto_enumTypes,
		MessageInfos:      file_axq_proto_msgTypes,
	}.Build()
	File_axq_proto = out.File
	file_axq_proto_rawDesc = nil
	file_axq_proto_goTypes = nil
	file_axq_proto_depIdxs = nil
}
